# Generated by Django 2.2.13 on 2020-09-10 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('status', models.TextField(choices=[('1', 'New'), ('2', 'In Progress'), ('3', 'Done')])),
            ],
        ),
        migrations.CreateModel(
            name='related_tasks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('TaskOne', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='First_Task', to='app.task')),
                ('TaskTwo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Second_Task', to='app.task')),
            ],
        ),
    ]
