# Generated by Django 2.2.13 on 2020-09-10 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.TextField(choices=[('New', 'New'), ('In Progress', 'In Progress'), ('Done', 'Done')]),
        ),
    ]
